name: hi-alex
on: push

jobs:
  email-people:
    runs-on: ubuntu-latest
    steps:
      - name: email friends
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ayy lmao
          to: alucas96@me.com,john.tomko1@gmail.com
          from: John Tomko
          html_body: I made a change to my GitHub repo, this time with proper capitalization. <a href="https://github.com/johntomko/smart-trainer">Check it out</a> or don't, I may somewhat give a fuck.
      - run: echo "lmao"
