name: hi-alex
on: push

jobs:
  email-people:
    runs-on: ubuntu-latest
    steps:
      - name: email friends
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ayy lmao
          to: alucas96@me.com,john.tomko1@gmail.com
          from: John Tomko
          body: i made a change to my git repo. check it out, or don't. i don't give a fuck
      - run: echo "lmao"
